server:
  port: 18000
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/leifchen/springcloud-sell-demo
          # git仓库地址下的相对地址，可以配置多个，用,分割
          search-paths: config-repo
          # git仓库的账号
          username:
          # git仓库的密码
          password:
          basedir: /config-repo/tmp/
  rabbitmq:
    host: 192.168.33.100
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:28761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.bus: debug
