server:
  port: 18002
spring:
  application:
    name: order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.33.100
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.33.100
    port: 6379
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
logging:
  level:
    org.springframework.cloud.openfeign: debug
test:
  name: LeifChen
  age: 18
