server:
  port: 18002
spring:
  application:
    name: order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.33.100
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.33.100
    port: 6379
  sleuth:
    feign:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://192.168.33.100:9411/
    sender:
      type: web
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
test:
  name: LeifChen
  age: 18
logging:
  level:
    org.springframework.cloud.openfeign: debug