server:
  port: 18001
spring:
  application:
    name: product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.33.100
    port: 5672
    username: guest
    password: guest
