spring:
  application:
    name: eureka
server:
  port: 28762
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:28761/eureka/
    register-with-eureka: true
    fetch-registry: false
  server:
    enable-self-preservation: false